name: bundles

on: workflow_call

jobs:
  files-changed:
    name: Detect which bundles had changes
    runs-on: ubuntu-20.04
    outputs:
      change_in_items_inspection: ${{ steps.changes.outputs.change_in_items_inspection }}
      change_in_bumps: ${{ steps.changes.outputs.change_in_bumps }}
      change_in_model_panel: ${{ steps.changes.outputs.change_in_model_panel }}
      change_in_toolshed_utils: ${{ steps.changes.outputs.change_in_toolshed_utils }}
      change_in_rest_server: ${{ steps.changes.outputs.change_in_rest_server }}
      change_in_neuron: ${{ steps.changes.outputs.change_in_neuron }}
      change_in_preset_mgr: ${{ steps.changes.outputs.change_in_preset_mgr }}
      change_in_sel_inspector: ${{ steps.changes.outputs.change_in_sel_inspector }}
      change_in_remote_control: ${{ steps.changes.outputs.change_in_remote_control }}
      change_in_ui: ${{ steps.changes.outputs.change_in_ui }}
      change_in_chem_group: ${{ steps.changes.outputs.change_in_chem_group }}
      change_in_render_by_attr: ${{ steps.changes.outputs.change_in_render_by_attr }}
      change_in_model_series: ${{ steps.changes.outputs.change_in_model_series }}
      change_in_crystal_contacts: ${{ steps.changes.outputs.change_in_crystal_contacts }}
      change_in_profile_grids: ${{ steps.changes.outputs.change_in_profile_grids }}
      change_in_connect_structure: ${{ steps.changes.outputs.change_in_connect_structure }}
      change_in_registration: ${{ steps.changes.outputs.change_in_registration }}
      change_in_swap_res: ${{ steps.changes.outputs.change_in_swap_res }}
      change_in_dssp: ${{ steps.changes.outputs.change_in_dssp }}
      change_in_exp_cmd: ${{ steps.changes.outputs.change_in_exp_cmd }}
      change_in_phenix_ui: ${{ steps.changes.outputs.change_in_phenix_ui }}
      change_in_residue_fit: ${{ steps.changes.outputs.change_in_residue_fit }}
      change_in_movie: ${{ steps.changes.outputs.change_in_movie }}
      change_in_scenes: ${{ steps.changes.outputs.change_in_scenes }}
      change_in_shape: ${{ steps.changes.outputs.change_in_shape }}
      change_in_md_crds: ${{ steps.changes.outputs.change_in_md_crds }}
      change_in_looking_glass: ${{ steps.changes.outputs.change_in_looking_glass }}
      change_in_renumber_residues: ${{ steps.changes.outputs.change_in_renumber_residues }}
      change_in_core_formats: ${{ steps.changes.outputs.change_in_core_formats }}
      change_in_linux_support: ${{ steps.changes.outputs.change_in_linux_support }}
      change_in_cage_builder: ${{ steps.changes.outputs.change_in_cage_builder }}
      change_in_clashes: ${{ steps.changes.outputs.change_in_clashes }}
      change_in_webservices: ${{ steps.changes.outputs.change_in_webservices }}
      change_in_change_chains: ${{ steps.changes.outputs.change_in_change_chains }}
      change_in_core: ${{ steps.changes.outputs.change_in_core }}
      change_in_buttons: ${{ steps.changes.outputs.change_in_buttons }}
      change_in_data_formats: ${{ steps.changes.outputs.change_in_data_formats }}
      change_in_sdf: ${{ steps.changes.outputs.change_in_sdf }}
      change_in_vrml: ${{ steps.changes.outputs.change_in_vrml }}
      change_in_test: ${{ steps.changes.outputs.change_in_test }}
      change_in_emdb_sff: ${{ steps.changes.outputs.change_in_emdb_sff }}
      change_in_foldseek: ${{ steps.changes.outputs.change_in_foldseek }}
      change_in_show_sequences: ${{ steps.changes.outputs.change_in_show_sequences }}
      change_in_markers: ${{ steps.changes.outputs.change_in_markers }}
      change_in_map_filter: ${{ steps.changes.outputs.change_in_map_filter }}
      change_in_basic_actions: ${{ steps.changes.outputs.change_in_basic_actions }}
      change_in_struts: ${{ steps.changes.outputs.change_in_struts }}
      change_in_mmcif: ${{ steps.changes.outputs.change_in_mmcif }}
      change_in_bild: ${{ steps.changes.outputs.change_in_bild }}
      change_in_save_command: ${{ steps.changes.outputs.change_in_save_command }}
      change_in_nifti: ${{ steps.changes.outputs.change_in_nifti }}
      change_in_help_viewer: ${{ steps.changes.outputs.change_in_help_viewer }}
      change_in_tug: ${{ steps.changes.outputs.change_in_tug }}
      change_in_shell: ${{ steps.changes.outputs.change_in_shell }}
      change_in_imod: ${{ steps.changes.outputs.change_in_imod }}
      change_in_add_charge: ${{ steps.changes.outputs.change_in_add_charge }}
      change_in_axes_planes: ${{ steps.changes.outputs.change_in_axes_planes }}
      change_in_morph: ${{ steps.changes.outputs.change_in_morph }}
      change_in_tape_measure: ${{ steps.changes.outputs.change_in_tape_measure }}
      change_in_color_key: ${{ steps.changes.outputs.change_in_color_key }}
      change_in_maestro: ${{ steps.changes.outputs.change_in_maestro }}
      change_in_modeller: ${{ steps.changes.outputs.change_in_modeller }}
      change_in_alignment_headers: ${{ steps.changes.outputs.change_in_alignment_headers }}
      change_in_volume_menu: ${{ steps.changes.outputs.change_in_volume_menu }}
      change_in_zone: ${{ steps.changes.outputs.change_in_zone }}
      change_in_segment: ${{ steps.changes.outputs.change_in_segment }}
      change_in_amber_info: ${{ steps.changes.outputs.change_in_amber_info }}
      change_in_diffplot: ${{ steps.changes.outputs.change_in_diffplot }}
      change_in_task_manager: ${{ steps.changes.outputs.change_in_task_manager }}
      change_in_atomic_lib: ${{ steps.changes.outputs.change_in_atomic_lib }}
      change_in_io: ${{ steps.changes.outputs.change_in_io }}
      change_in_bond_rot: ${{ steps.changes.outputs.change_in_bond_rot }}
      change_in_pdb_bio: ${{ steps.changes.outputs.change_in_pdb_bio }}
      change_in_toolbar: ${{ steps.changes.outputs.change_in_toolbar }}
      change_in_bogus: ${{ steps.changes.outputs.change_in_bogus }}
      change_in_mouse_modes: ${{ steps.changes.outputs.change_in_mouse_modes }}
      change_in_label: ${{ steps.changes.outputs.change_in_label }}
      change_in_bundle_builder: ${{ steps.changes.outputs.change_in_bundle_builder }}
      change_in_rotamer_libs: ${{ steps.changes.outputs.change_in_rotamer_libs }}
      change_in_surface: ${{ steps.changes.outputs.change_in_surface }}
      change_in_cmd_line: ${{ steps.changes.outputs.change_in_cmd_line }}
      change_in_gltf: ${{ steps.changes.outputs.change_in_gltf }}
      change_in_wavefront_obj: ${{ steps.changes.outputs.change_in_wavefront_obj }}
      change_in_crystal: ${{ steps.changes.outputs.change_in_crystal }}
      change_in_hbonds: ${{ steps.changes.outputs.change_in_hbonds }}
      change_in_vive: ${{ steps.changes.outputs.change_in_vive }}
      change_in_stl: ${{ steps.changes.outputs.change_in_stl }}
      change_in_hkcage: ${{ steps.changes.outputs.change_in_hkcage }}
      change_in_build_structure: ${{ steps.changes.outputs.change_in_build_structure }}
      change_in_atomic: ${{ steps.changes.outputs.change_in_atomic }}
      change_in_speech: ${{ steps.changes.outputs.change_in_speech }}
      change_in_nrrd: ${{ steps.changes.outputs.change_in_nrrd }}
      change_in_pdb_matrices: ${{ steps.changes.outputs.change_in_pdb_matrices }}
      change_in_file_history: ${{ steps.changes.outputs.change_in_file_history }}
      change_in_pdb_images: ${{ steps.changes.outputs.change_in_pdb_images }}
      change_in_medical_imaging: ${{ steps.changes.outputs.change_in_medical_imaging }}
      change_in_ihm: ${{ steps.changes.outputs.change_in_ihm }}
      change_in_nih_presets: ${{ steps.changes.outputs.change_in_nih_presets }}
      change_in_lighting_gui: ${{ steps.changes.outputs.change_in_lighting_gui }}
      change_in_mask: ${{ steps.changes.outputs.change_in_mask }}
      change_in_iupac: ${{ steps.changes.outputs.change_in_iupac }}
      change_in_map: ${{ steps.changes.outputs.change_in_map }}
      change_in_centroids: ${{ steps.changes.outputs.change_in_centroids }}
      change_in_blastprotein: ${{ steps.changes.outputs.change_in_blastprotein }}
      change_in_meeting: ${{ steps.changes.outputs.change_in_meeting }}
      change_in_vtk: ${{ steps.changes.outputs.change_in_vtk }}
      change_in_unit_cell: ${{ steps.changes.outputs.change_in_unit_cell }}
      change_in_check_waters: ${{ steps.changes.outputs.change_in_check_waters }}
      change_in_crosslinks: ${{ steps.changes.outputs.change_in_crosslinks }}
      change_in_altloc_explorer: ${{ steps.changes.outputs.change_in_altloc_explorer }}
      change_in_arrays: ${{ steps.changes.outputs.change_in_arrays }}
      change_in_function_key: ${{ steps.changes.outputs.change_in_function_key }}
      change_in_alphafold: ${{ steps.changes.outputs.change_in_alphafold }}
      change_in_smooth_lines: ${{ steps.changes.outputs.change_in_smooth_lines }}
      change_in_color_actions: ${{ steps.changes.outputs.change_in_color_actions }}
      change_in_deep_mutational_scan: ${{ steps.changes.outputs.change_in_deep_mutational_scan }}
      change_in_shortcuts: ${{ steps.changes.outputs.change_in_shortcuts }}
      change_in_nucleotides: ${{ steps.changes.outputs.change_in_nucleotides }}
      change_in_positions: ${{ steps.changes.outputs.change_in_positions }}
      change_in_atom_search: ${{ steps.changes.outputs.change_in_atom_search }}
      change_in_segger: ${{ steps.changes.outputs.change_in_segger }}
      change_in_dist_monitor: ${{ steps.changes.outputs.change_in_dist_monitor }}
      change_in_mcopy: ${{ steps.changes.outputs.change_in_mcopy }}
      change_in_medical_toolbar: ${{ steps.changes.outputs.change_in_medical_toolbar }}
      change_in_sim_matrices: ${{ steps.changes.outputs.change_in_sim_matrices }}
      change_in_sideview: ${{ steps.changes.outputs.change_in_sideview }}
      change_in_log: ${{ steps.changes.outputs.change_in_log }}
      change_in_cellpack: ${{ steps.changes.outputs.change_in_cellpack }}
      change_in_to_quest: ${{ steps.changes.outputs.change_in_to_quest }}
      change_in_tug_ligands: ${{ steps.changes.outputs.change_in_tug_ligands }}
      change_in_image_formats: ${{ steps.changes.outputs.change_in_image_formats }}
      change_in_uniprot: ${{ steps.changes.outputs.change_in_uniprot }}
      change_in_pick_blobs: ${{ steps.changes.outputs.change_in_pick_blobs }}
      change_in_read_pbonds: ${{ steps.changes.outputs.change_in_read_pbonds }}
      change_in_match_maker: ${{ steps.changes.outputs.change_in_match_maker }}
      change_in_spacenavigator: ${{ steps.changes.outputs.change_in_spacenavigator }}
      change_in_pdb_lib: ${{ steps.changes.outputs.change_in_pdb_lib }}
      change_in_viperdb: ${{ steps.changes.outputs.change_in_viperdb }}
      change_in_geometry: ${{ steps.changes.outputs.change_in_geometry }}
      change_in_segmentations: ${{ steps.changes.outputs.change_in_segmentations }}
      change_in_map_data: ${{ steps.changes.outputs.change_in_map_data }}
      change_in_map_eraser: ${{ steps.changes.outputs.change_in_map_eraser }}
      change_in_rna_layout: ${{ steps.changes.outputs.change_in_rna_layout }}
      change_in_mol2: ${{ steps.changes.outputs.change_in_mol2 }}
      change_in_std_commands: ${{ steps.changes.outputs.change_in_std_commands }}
      change_in_seqalign: ${{ steps.changes.outputs.change_in_seqalign }}
      change_in_color_globe: ${{ steps.changes.outputs.change_in_color_globe }}
      change_in_graphics: ${{ steps.changes.outputs.change_in_graphics }}
      change_in_swapaa: ${{ steps.changes.outputs.change_in_swapaa }}
      change_in_leap_motion: ${{ steps.changes.outputs.change_in_leap_motion }}
      change_in_esmfold: ${{ steps.changes.outputs.change_in_esmfold }}
      change_in_alignment_algs: ${{ steps.changes.outputs.change_in_alignment_algs }}
      change_in_rotamers: ${{ steps.changes.outputs.change_in_rotamers }}
      change_in_list_info: ${{ steps.changes.outputs.change_in_list_info }}
      change_in_coulombic: ${{ steps.changes.outputs.change_in_coulombic }}
      change_in_mole: ${{ steps.changes.outputs.change_in_mole }}
      change_in_nmrstar: ${{ steps.changes.outputs.change_in_nmrstar }}
      change_in_webcam: ${{ steps.changes.outputs.change_in_webcam }}
      change_in_dicom: ${{ steps.changes.outputs.change_in_dicom }}
      change_in_topography: ${{ steps.changes.outputs.change_in_topography }}
      change_in_pubchem: ${{ steps.changes.outputs.change_in_pubchem }}
      change_in_scheme_mgr: ${{ steps.changes.outputs.change_in_scheme_mgr }}
      change_in_map_series: ${{ steps.changes.outputs.change_in_map_series }}
      change_in_realsense: ${{ steps.changes.outputs.change_in_realsense }}
      change_in_storm: ${{ steps.changes.outputs.change_in_storm }}
      change_in_pdb: ${{ steps.changes.outputs.change_in_pdb }}
      change_in_seq_view: ${{ steps.changes.outputs.change_in_seq_view }}
      change_in_signal_viewer: ${{ steps.changes.outputs.change_in_signal_viewer }}
      change_in_open_command: ${{ steps.changes.outputs.change_in_open_command }}
      change_in_mmtf: ${{ steps.changes.outputs.change_in_mmtf }}
      change_in_struct_measure: ${{ steps.changes.outputs.change_in_struct_measure }}
      change_in_animations: ${{ steps.changes.outputs.change_in_animations }}
      change_in_orthopick: ${{ steps.changes.outputs.change_in_orthopick }}
      change_in_bug_reporter: ${{ steps.changes.outputs.change_in_bug_reporter }}
      change_in_mlp: ${{ steps.changes.outputs.change_in_mlp }}
      change_in_interfaces: ${{ steps.changes.outputs.change_in_interfaces }}
      change_in_addh: ${{ steps.changes.outputs.change_in_addh }}
      change_in_smiles: ${{ steps.changes.outputs.change_in_smiles }}
      change_in_map_fit: ${{ steps.changes.outputs.change_in_map_fit }}
      change_in_viewdockx: ${{ steps.changes.outputs.change_in_viewdockx }}
      change_in_dock_prep: ${{ steps.changes.outputs.change_in_dock_prep }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ steps.changes.outputs.github.token }}
          filters: .github/bundle-file-filters.yml
