name: srcapps

on: workflow_call

jobs:
  files-changed:
    name: Detect which prerequsites had changes
    runs-on: ubuntu-20.04
    outputs:
      change_in_chimerax: ${{ steps.changes.outputs.change_in_chimerax }}
      change_in_scanpdb: ${{ steps.changes.outputs.change_in_scanpdb }}
      change_in_icon-tools: ${{ steps.changes.outputs.change_in_icon-tools }}
      change_in_moduleapp: ${{ steps.changes.outputs.change_in_moduleapp }}
      change_in_valgrind: ${{ steps.changes.outputs.change_in_valgrind }}
      change_in_structcomp: ${{ steps.changes.outputs.change_in_structcomp }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/srcapp-file-filters.yml
